Version: 1.0.0
# This sets the default options for the worldguard flags.
# True = Allow and False = Deny
RegionFlagDefaults:
    pvp: true
    mob-damage: true
    mob-spawning: true
    creeper-explosion: true
    ghast-fireball: true
    tnt: true
    lighter: true
    fire-spread: true
    lava-fire: true
    lightning: true
    chest-access: false
    water-flow: true
    lava-flow: true
    use: true
    leaf-decay: true
    # Valid tags are %PropertyName% for the property name and %Owner% for the owners name.
    greeting: Welcome to %PropertyName% owned by %Owner%
    greetingnoowner: Welcome to %PropertyName%
    farewell: You are now leaving %PropertyName%