name: PropertyGroup
version: 1.0
main: com.randrdevelopment.propertygroup.PropertyGroup
author: FireBall1725

commands:
   property:
      description: Main command for Property Groups.
      usage: /<command> help
      
permissions:
    propertygroup.*:
        description: Gives access to all property group commands
        children:
            doorman.create: true
            
    propertygroup.create:
        description: Allows you to create a property group
        default: op