name: PropertyGroup
version: @VERSION@
#version: 1.1
main: com.randrdevelopment.propertygroup.PropertyGroup
author: FireBall1725

commands:
   property:
      description: Main command for Property Groups.
      usage: /<command> help
   cp:
      description: Alias for Create Property.
      usage: /<command> region user
   ptp:
      description: Alias for Teleport to Property.
      usage: /<command> property [user]
   add:
      description: Alias for adding user to property.
      usage: /<command> <player> [property]

permissions:
    propertygroup.*:
        description: Gives access to all property group commands
        children:
            propertygroup.create: true
            propertygroup.reload: true    
            propertygroup.createproperty: true 
            propertygroup.deleteproperty: true
            propertygroup.teleport: true
            propertygroup.addoverride: true

    propertygroup.create:
        description: Allows you to create a property group
        default: op

    propertygroup.reload:
        description: Reload the configuration files
        default: op
        
    propertygroup.createproperty:
        description: Allows the user to create a property
        default: op
        
    propertygroup.deleteproperty:
        description: Allows the user to delete a property
        default: op
        
    propertygroup.teleport:
        description: Allows the user to teleport to properties
        default: op
        
    propertygroup.addoverride:
        description: Allows the user to add a player to an island that isnt theirs
        default: op