name: PropertyGroup
version: @VERSION@
main: com.randrdevelopment.propertygroup.PropertyGroup
author: FireBall1725

commands:
   property:
      description: Main command for Property Groups.
      usage: /<command> help

permissions:
    propertygroup.*:
        description: Gives access to all property group commands
        children:
            propertygroup.create: true
            propertygroup.reload: true    
            propertygroup.createproperty: true        

    propertygroup.create:
        description: Allows you to create a property group
        default: op

    propertygroup.reload:
        description: Reload the configuration files
        default: op
        
    propertygroup.createproperty:
        description: Allows the user to create a property
        default: op